In [24]:
import tensorflow as tf
import numpy as np
import pickle

In [23]:
np.__version__

'1.26.4'

In [26]:
tf.__version__

'2.16.1'

In [14]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input((10, 2)))
model.add(tf.keras.layers.LSTM(30))
model.add(tf.keras.layers.Dense(8, use_bias=False, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 30)             │         3,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 8)              │           240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,209 (16.44 KB)

 Trainable params: 4,209 (16.44 KB)

 Non-trainable params: 0 (0.00 B)

[<KerasVariable shape=(2, 120), dtype=float32, path=sequential/lstm/lstm_cell/kernel>,
 <KerasVariable shape=(30, 120), dtype=float32, path=sequential/lstm/lstm_cell/recurrent_kernel>,
 <KerasVariable shape=(120,), dtype=float32, path=sequential/lstm/lstm_cell/bias>,
 <KerasVariable shape=(30, 8), dtype=float32, path=sequential/dense/kernel>,
 <KerasVariable shape=(8, 1), dtype=float32, path=sequential/dense_1/kernel>,
 <KerasVariable shape=(1,), dtype=float32, path=sequential/dense_1/bias>]

In [8]:
model.compile(optimizer='adam', loss='mse')

In [9]:
model.fit(np.array([1, 2, 3, 7, 11]).astype(float), np.array([3, 5, 7, 15, 23]).astype(float), epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 162.8380
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 161.3130
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 159.7968
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 158.2894
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 156.7909
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 155.3015
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 153.8212
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 152.3501
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 150.8883
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 149.4357
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 147.9924
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 146.5584
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 145.1337
Epoch 14/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 143.7183
Epoch 15/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 142.3122
Epoch 

In [97]:
model.predict(np.array([5.]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[11.024815]], dtype=float32)

In [19]:
from tf2jModel.converter import Converter

In [20]:
jmodel_tf = Converter()
jmodel_tf.adapt(model)
jmodel_tf.convert("test.jmodel")

TypeError: Layer LSTM is not supported for jModel=0.0.1

In [1]:
import jmodel

In [2]:
model_optimized = jmodel.model()
model_optimized.load_model('test.jmodel')

In [3]:
import numpy as np
import time

In [4]:
a = np.array([1.])
t = time.time()
model_optimized.predict(a)
print(time.time() - t)
t = time.time()
model.predict(a, verbose=0)
print(time.time() - t)


0.008014440536499023


NameError: name 'model' is not defined

In [5]:
a = np.array([1]).dot(model_optimized.layers[0].weights[0]) + model_optimized.layers[0].weights[1]
print(a)
print(model_optimized.layers[0].feed([1]))

[-0.81767926 -0.50544365 -0.04764627 -0.97416814 -0.37854484  0.17378078
  0.16316418  0.66884722 -0.18431115  0.29467995 -0.57708365  0.69327667
  0.58437225 -0.01716352  0.62169321 -0.60071535]
[-0.81767926 -0.50544365 -0.04764627 -0.97416814 -0.37854484  0.17378078
  0.16316418  0.66884722 -0.18431115  0.29467995 -0.57708365  0.69327667
  0.58437225 -0.01716352  0.62169321 -0.60071535]


In [6]:
b = np.maximum(a.dot(model_optimized.layers[1].weights[0]), 0)
print(b)
print(model_optimized.layers[1].feed(a))

[0.         0.         0.         0.         0.         0.
 0.         3.27112032]
[0.         0.         0.         0.         0.         0.
 0.         3.27112032]


In [8]:
model_optimized.layers[1].activation

<function jmodel.Activation.relu(input_array)>

In [9]:
c = b.dot(model_optimized.layers[2].weights[0]) + model_optimized.layers[2].weights[1]
c

array([3.06902247])

In [10]:
model_optimized.predict([1])

array([3.06902247])

In [126]:
model.predict(np.array([1.]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[3.0690227]], dtype=float32)

In [17]:
model.weights

[<KerasVariable shape=(2, 120), dtype=float32, path=sequential/lstm/lstm_cell/kernel>,
 <KerasVariable shape=(30, 120), dtype=float32, path=sequential/lstm/lstm_cell/recurrent_kernel>,
 <KerasVariable shape=(120,), dtype=float32, path=sequential/lstm/lstm_cell/bias>,
 <KerasVariable shape=(30, 8), dtype=float32, path=sequential/dense/kernel>,
 <KerasVariable shape=(8, 1), dtype=float32, path=sequential/dense_1/kernel>,
 <KerasVariable shape=(1,), dtype=float32, path=sequential/dense_1/bias>]

In [18]:
model_optimized.layers

In [12]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

def lstm_feedforward(inputs, lstm_units, return_sequences, activation):
    # Initialize weights and biases
    input_dim = inputs.shape[2]
    hidden_dim = lstm_units

    # Input-to-hidden weights
    w_ih = np.random.randn(input_dim, 4 * hidden_dim) * 0.01
    # Hidden-to-hidden weights
    w_hh = np.random.randn(hidden_dim, 4 * hidden_dim) * 0.01
    # Biases
    b = np.zeros(4 * hidden_dim)

    seq_len = inputs.shape[1]

    hiddens = []
    c = np.zeros((inputs.shape[0], hidden_dim))  # Cell state initialization
    h = np.zeros((inputs.shape[0], hidden_dim))  # Hidden state initialization

    for t in range(seq_len):
        x_t = inputs[:, t, :]

        # LSTM cell operations
        gates = np.dot(x_t, w_ih) + np.dot(h, w_hh) + b
        input_gate = sigmoid(gates[:, :hidden_dim])
        forget_gate = sigmoid(gates[:, hidden_dim:2*hidden_dim])
        output_gate = sigmoid(gates[:, 2*hidden_dim:3*hidden_dim])
        candidate_cell = tanh(gates[:, 3*hidden_dim:])

        c = forget_gate * c + input_gate * candidate_cell
        h = output_gate * tanh(c)

        hiddens.append(h)

    if return_sequences:
        output = np.array(hiddens).transpose(1, 0, 2)
    else:
        output = h

    if activation is not None:
        output = activation(output)

    return output

# Example usage
input_array = np.random.randn(5, 10, 3)  # Shape: (None, 10, 3)
lstm_units = 30
return_sequences = True
activation = None  # No activation function for demonstration purpose

output = lstm_feedforward(input_array, lstm_units, return_sequences, activation)

print("Output shape:", output.shape)  # Expected output shape: (None, 30) if return_sequences=False


Output shape: (5, 10, 30)
